const { toCamelCase } = require('./index')

const getImports = libs =>
  libs
    .map(lib => {
      return `import ${toCamelCase(lib.name)} from '@${lib.type}/${lib.name}'`
    })
    .join('\n')

exports.generateEntryScript = function(libs) {
  const importsSrc = getImports(libs)
  const exportsSrc = libs.map(lib => toCamelCase(lib.name)).join(',\n  ')

  const resultSrc = `// Generated by cli
${importsSrc}

export default {
  ${exportsSrc},
}
`
  return resultSrc
}

exports.generateGlobalScript = function(libs) {
  const importsSrc = getImports(libs)
  const usesSrc = libs
    .map(lib => `Vue.use(${toCamelCase(lib.name)})`)
    .join('\n  ')

  const resultSrc = `// Generated by cli
${importsSrc}

export default function installGlobal(Vue) {
  ${usesSrc}
}
`
  return resultSrc
}
