// Generated by cli
import DatePicker from '@blocks/date-picker'
import GtTablePagination from '@blocks/gt-table-pagination'
import GtExample from '@components/gt-example'
import GtInput from '@components/gt-input'
import GtTable from '@components/gt-table'

export default function installGlobal(Vue) {
  Vue.use(DatePicker)
  Vue.use(GtTablePagination)
  Vue.use(GtExample)
  Vue.use(GtInput)
  Vue.use(GtTable)
}
