// Generated by cli
import DatePicker from '@blocks/date-picker'
import GtTablePagination from '@blocks/gt-table-pagination'
import GtExample from '@components/gt-example'
import GtInput from '@components/gt-input'
import GtTable from '@components/gt-table'

export default {
  DatePicker,
  GtTablePagination,
  GtExample,
  GtInput,
  GtTable,
}
